import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./vendor.css";
import Sidebar from "@/components/vendorsidebar";
import { SidebarProvider } from "@/components/sidebarprovider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shoppersky",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <div className="flex min-h-screen bg-white dark:bg-zinc-900">
            {/* Fixed sidebar */}
            <div className="fixed top-0 left-0 h-screen w-16 sm:w-64 transition-all duration-300 z-50">
              <Sidebar />
            </div>

            {/* Main content area with responsive padding */}
            <main className="flex-1 pl-16 sm:pl-64 transition-all duration-300">
              {/* Background */}
              <div className="relative min-h-screen overflow-y-auto bg-gradient-to-br from-gray-50 via-purple-50/30 to-blue-50/40 dark:from-zinc-900 dark:via-purple-950/20 dark:to-blue-950/30">
                <div className="absolute inset-0 bg-gradient-to-br from-purple-100/20 via-transparent to-blue-100/20 dark:from-purple-900/10 dark:via-transparent dark:to-blue-900/10 pointer-events-none" />
                <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_50%,rgba(147,51,234,0.03),transparent_50%)] dark:bg-[radial-gradient(circle_at_50%_50%,rgba(147,51,234,0.05),transparent_50%)] pointer-events-none" />

                {/* Page content */}
                <div className="relative z-10">{children}</div>
              </div>
            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
